import { types } from "replugged";
import GeneralDiscordTypes from "discord-types/general";
import type { Store as StoreType } from "replugged/dist/renderer/modules/common/flux";
import { ContextMenuProps } from "replugged/dist/renderer/modules/components/ContextMenu";
import util from "replugged/util";

export namespace Types {
  export import DefaultTypes = types;
  export type MenuProps = ContextMenuProps["ContextMenu"];
  export type Tree = util.Tree;
  export type Store = StoreType;
  export type OriginalChannel = GeneralDiscordTypes.Channel;
  export type Guild = GeneralDiscordTypes.Guild;
  export type Role = GeneralDiscordTypes.Role;
  export type User = GeneralDiscordTypes.User;
  export interface RelationshipStore extends Store {
    getFriendCount: DefaultTypes.AnyFunction;
    getFriendIDs: DefaultTypes.AnyFunction;
    getNickname: DefaultTypes.AnyFunction;
    getOutgoingCount: DefaultTypes.AnyFunction;
    getPendingCount: DefaultTypes.AnyFunction;
    getRelationshipCount: DefaultTypes.AnyFunction;
    getRelationshipType: DefaultTypes.AnyFunction;
    getRelationships: DefaultTypes.AnyFunction;
    getSince: DefaultTypes.AnyFunction;
    getSinces: DefaultTypes.AnyFunction;
    initialize: DefaultTypes.AnyFunction;
    isBlocked: DefaultTypes.AnyFunction;
    isFriend: DefaultTypes.AnyFunction;
  }
  export interface MediaEngineStore extends Store {
    getAecDump: DefaultTypes.AnyFunction;
    getAttenuateWhileSpeakingOthers: DefaultTypes.AnyFunction;
    getAttenuateWhileSpeakingSelf: DefaultTypes.AnyFunction;
    getAttenuation: DefaultTypes.AnyFunction;
    getAudioSubsystem: DefaultTypes.AnyFunction;
    getAutomaticGainControl: DefaultTypes.AnyFunction;
    getAv1Enabled: DefaultTypes.AnyFunction;
    getCameraComponent: DefaultTypes.AnyFunction;
    getDebugLogging: DefaultTypes.AnyFunction;
    getEchoCancellation: DefaultTypes.AnyFunction;
    getEnableSilenceWarning: DefaultTypes.AnyFunction;
    getEverSpeakingWhileMuted: DefaultTypes.AnyFunction;
    getExperimentalEncoders: DefaultTypes.AnyFunction;
    getExperimentalSoundshare: DefaultTypes.AnyFunction;
    getGoLiveContext: DefaultTypes.AnyFunction;
    getGoLiveSource: DefaultTypes.AnyFunction;
    getH265Enabled: DefaultTypes.AnyFunction;
    getHardwareH264: DefaultTypes.AnyFunction;
    getInputDetected: DefaultTypes.AnyFunction;
    getInputDeviceId: DefaultTypes.AnyFunction;
    getInputDevices: DefaultTypes.AnyFunction;
    getInputVolume: DefaultTypes.AnyFunction;
    getLocalPan: DefaultTypes.AnyFunction;
    getLocalVolume: DefaultTypes.AnyFunction;
    getLoopback: DefaultTypes.AnyFunction;
    getMediaEngine: DefaultTypes.AnyFunction;
    getMode: DefaultTypes.AnyFunction;
    getModeOptions: DefaultTypes.AnyFunction;
    getNoInputDetectedNotice: DefaultTypes.AnyFunction;
    getNoiseCancellation: DefaultTypes.AnyFunction;
    getNoiseSuppression: DefaultTypes.AnyFunction;
    getOpenH264: DefaultTypes.AnyFunction;
    getOutputDeviceId: DefaultTypes.AnyFunction;
    getOutputDevices: DefaultTypes.AnyFunction;
    getOutputVolume: DefaultTypes.AnyFunction;
    getPacketDelay: DefaultTypes.AnyFunction;
    getQoS: DefaultTypes.AnyFunction;
    getSettings: DefaultTypes.AnyFunction;
    getShortcuts: DefaultTypes.AnyFunction;
    getSoundshareEnabled: DefaultTypes.AnyFunction;
    getState: DefaultTypes.AnyFunction;
    getSupportedSecureFramesProtocolVersion: DefaultTypes.AnyFunction;
    getVideoComponent: DefaultTypes.AnyFunction;
    getVideoDeviceId: DefaultTypes.AnyFunction;
    getVideoDevices: DefaultTypes.AnyFunction;
    getVideoHook: DefaultTypes.AnyFunction;
    getVideoStreamParameters: DefaultTypes.AnyFunction;
    getVideoToggleState: DefaultTypes.AnyFunction;
    hasClipsSource: DefaultTypes.AnyFunction;
    hasContext: DefaultTypes.AnyFunction;
    isAdvancedVoiceActivitySupported: DefaultTypes.AnyFunction;
    isAecDumpSupported: DefaultTypes.AnyFunction;
    isAnyLocalVideoAutoDisabled: DefaultTypes.AnyFunction;
    isAutomaticGainControlSupported: DefaultTypes.AnyFunction;
    isDeaf: DefaultTypes.AnyFunction;
    isEnabled: DefaultTypes.AnyFunction;
    isExperimentalEncodersSupported: DefaultTypes.AnyFunction;
    isHardwareMute: DefaultTypes.AnyFunction;
    isInteractionRequired: DefaultTypes.AnyFunction;
    isLocalMute: DefaultTypes.AnyFunction;
    isLocalVideoAutoDisabled: DefaultTypes.AnyFunction;
    isLocalVideoDisabled: DefaultTypes.AnyFunction;
    isMediaFilterSettingLoading: DefaultTypes.AnyFunction;
    isMute: DefaultTypes.AnyFunction;
    isNativeAudioPermissionReady: DefaultTypes.AnyFunction;
    isNoiseCancellationError: DefaultTypes.AnyFunction;
    isNoiseCancellationSupported: DefaultTypes.AnyFunction;
    isNoiseSuppressionSupported: DefaultTypes.AnyFunction;
    isScreenSharing: DefaultTypes.AnyFunction;
    isSelfDeaf: DefaultTypes.AnyFunction;
    isSelfMute: DefaultTypes.AnyFunction;
    isSelfMutedTemporarily: DefaultTypes.AnyFunction;
    isSimulcastSupported: DefaultTypes.AnyFunction;
    isSoundSharing: DefaultTypes.AnyFunction;
    isSupported: DefaultTypes.AnyFunction;
    isVideoAvailable: DefaultTypes.AnyFunction;
    isVideoEnabled: DefaultTypes.AnyFunction;
    setCanHavePriority: DefaultTypes.AnyFunction;
    supports: DefaultTypes.AnyFunction;
    supportsDisableLocalVideo: DefaultTypes.AnyFunction;
    supportsEnableSoundshare: DefaultTypes.AnyFunction;
    supportsExperimentalSoundshare: DefaultTypes.AnyFunction;
    supportsInApp: DefaultTypes.AnyFunction;
    supportsScreenSoundshare: DefaultTypes.AnyFunction;
    supportsVideoHook: DefaultTypes.AnyFunction;
  }
  export interface MediaEngineUtils {
    enable: DefaultTypes.AnyFunction;
    enableSoundshare: DefaultTypes.AnyFunction;
    interact: DefaultTypes.AnyFunction;
    reset: DefaultTypes.AnyFunction;
    setAV1Enabled: DefaultTypes.AnyFunction;
    setAecDump: DefaultTypes.AnyFunction;
    setAttenuation: DefaultTypes.AnyFunction;
    setAudioSubsystem: DefaultTypes.AnyFunction;
    setAutomaticGainControl: DefaultTypes.AnyFunction;
    setDebugLogging: DefaultTypes.AnyFunction;
    setDisableLocalVideo: DefaultTypes.AnyFunction;
    setEchoCancellation: DefaultTypes.AnyFunction;
    setExperimentalEncoders: DefaultTypes.AnyFunction;
    setExperimentalSoundshare: DefaultTypes.AnyFunction;
    setGoLiveSource: DefaultTypes.AnyFunction;
    setH265Enabled: DefaultTypes.AnyFunction;
    setHardwareH264: DefaultTypes.AnyFunction;
    setInputDevice: DefaultTypes.AnyFunction;
    setInputVolume: DefaultTypes.AnyFunction;
    setLocalPan: DefaultTypes.AnyFunction;
    setLocalVolume: DefaultTypes.AnyFunction;
    setLoopback: DefaultTypes.AnyFunction;
    setMode: DefaultTypes.AnyFunction;
    setNoiseCancellation: DefaultTypes.AnyFunction;
    setNoiseSuppression: DefaultTypes.AnyFunction;
    setOpenH264: DefaultTypes.AnyFunction;
    setOutputDevice: DefaultTypes.AnyFunction;
    setOutputVolume: DefaultTypes.AnyFunction;
    setQoS: DefaultTypes.AnyFunction;
    setSilenceWarning: DefaultTypes.AnyFunction;
    setTemporarySelfMute: DefaultTypes.AnyFunction;
    setVideoDevice: DefaultTypes.AnyFunction;
    setVideoEnabled: DefaultTypes.AnyFunction;
    setVideoHook: DefaultTypes.AnyFunction;
    toggleLocalMute: DefaultTypes.AnyFunction;
    toggleLocalSoundboardMute: DefaultTypes.AnyFunction;
    toggleSelfDeaf: DefaultTypes.AnyFunction;
    toggleSelfMute: DefaultTypes.AnyFunction;
  }
}
export default Types;
